name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  # Phase 1: Build platform binaries and tools
  generate-help-md:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: nesbox/tic-80
          ref: sokol
          submodules: recursive
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install
        run: |
          sudo apt-get install build-essential libxi-dev libxcursor-dev libasound2-dev libgl-dev -y

      - name: Build
        run: |
          cd build
          cmake -DBUILD_WITH_ALL=ON -DBUILD_TOOLS=ON ..
          cmake --build . --parallel

      - name: Export help.md and version.md
        run: |
          build/bin/tic80 --cli --fs=. --cmd='export help help.md'
          build/bin/tic80 --cli --fs=. --cmd="help version" > version.txt

      - name: Upload help.md and version.txt
        uses: actions/upload-artifact@v4
        with:
          name: help-md
          path: |
            help.md
            version.txt

      - name: Upload xplode
        uses: actions/upload-artifact@v4
        with:
          name: xplode
          path: |
            build/bin/xplode

  webapp:
    runs-on: ubuntu-latest

    steps:
      - uses: mymindstorm/setup-emsdk@v14

      - uses: actions/checkout@v4
        with:
          repository: nesbox/tic-80
          ref: sokol
          submodules: recursive
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Build all
        run: |
          cd build
          emcmake cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_IPO=ON -DBUILD_WITH_ALL=ON ..
          cmake --build . --parallel

      - name: Deploy
        uses: actions/upload-artifact@v4
        with:
          name: "tic80-webapp"
          path: |
            build/bin/*

  windows:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
        with:
          repository: nesbox/tic-80
          ref: sokol
          submodules: recursive
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Build
        shell: cmd
        run: |
          cd build
          cmake -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release -DBUILD_IPO=ON -DBUILD_WITH_ALL=ON ..
          cmake --build . --parallel

      - name: Zip tic80.exe
        run: |
          cd build/bin
          zip tic80.zip tic80.exe

      - name: Deploy
        uses: actions/upload-artifact@v4
        with:
          name: "tic80-windows"
          path: build/bin/tic80.zip

  macos:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4
        with:
          repository: nesbox/tic-80
          ref: sokol
          submodules: recursive
          fetch-depth: 0

      - name: Install
        run: brew uninstall --ignore-dependencies libidn2

      - name: Build
        run: |
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_IPO=ON -DBUILD_WITH_ALL=ON ..
          cmake --build . --parallel
          cpack

      - name: Rename DMG
        run: |
          cd build
          mv TIC-80*.dmg tic80.dmg

      - name: Deploy
        uses: actions/upload-artifact@v4
        with:
          name: "tic80-macos"
          path: build/tic80.dmg

  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: nesbox/tic-80
          ref: sokol
          submodules: recursive
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install
        run: |
          sudo apt-get install build-essential libxi-dev libxcursor-dev libasound2-dev libgl-dev libfuse2 -y

      - name: Build
        run: |
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_IPO=ON -DBUILD_WITH_ALL=ON ..
          cmake --build . --parallel

      - name: Build AppImage
        run: |
          chmod +x build-appimage.sh
          ./build-appimage.sh

      - name: Deploy AppImage
        uses: actions/upload-artifact@v4
        with:
          name: "tic80-appimage"
          path: TIC-80.AppImage

  # Phase 2: Process data
  update-hashes:
    runs-on: ubuntu-latest
    needs:
      - windows
      - macos
      - linux

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download tic80-windows artifact
        uses: actions/download-artifact@v4
        with:
          name: tic80-windows
          path: public/download

      - name: Download tic80-macos artifact
        uses: actions/download-artifact@v4
        with:
          name: tic80-macos
          path: public/download

      - name: Download tic80-appimage artifact
        uses: actions/download-artifact@v4
        with:
          name: tic80-appimage
          path: public/download

      - name: Calculate hashes
        run: go run scripts/calc-hashes.go

      - name: Upload hashes
        uses: actions/upload-artifact@v4
        with:
          name: hashes
          path: src/data/hashes.json

  # Phase 3: Generate and deploy website
  explode-carts:
    runs-on: ubuntu-latest
    needs:
      - generate-help-md

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build and run sync.go
        if: github.event_name == 'schedule'
        run: go run scripts/sync.go

      - name: Commit changes
        if: github.event_name == 'schedule'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update data files" || echo "No changes to commit"
          git push

      - name: Download xplode artifact
        uses: actions/download-artifact@v4
        with:
          name: xplode
          path: scripts

      - name: Make xplode executable
        run: chmod +x scripts/xplode

      - name: Run explode carts
        run: go run scripts/xplode.go

      - name: Upload exploded data
        uses: actions/upload-artifact@v4
        with:
          name: exploded-carts
          path: |
            src/data/*.json
            public/**/*.json
            public/**/*.tic

  generate-tree:
    runs-on: ubuntu-latest
    needs:
      - explode-carts

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download exploded data artifact
        uses: actions/download-artifact@v4
        with:
          name: exploded-carts
          path: public

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Generate tree structure
        run: go run scripts/gen-tree.go

      - name: Upload tree structure
        uses: actions/upload-artifact@v4
        with:
          name: tree-structure
          path: |
            public/tree.json
            public/play/tree.json
            public/dev/tree.json
            public/dev/**/tree.json

  build-and-deploy:
    runs-on: ubuntu-latest
    needs:
      - webapp
      - windows
      - macos
      - linux
      - generate-tree

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download tic80-webapp artifact
        uses: actions/download-artifact@v4
        with:
          name: tic80-webapp
          path: public

      - name: Download tic80-windows artifact
        uses: actions/download-artifact@v4
        with:
          name: tic80-windows
          path: public/download

      - name: Download tic80-macos artifact
        uses: actions/download-artifact@v4
        with:
          name: tic80-macos
          path: public/download

      - name: Download tic80-appimage artifact
        uses: actions/download-artifact@v4
        with:
          name: tic80-appimage
          path: public/download

      - name: Download exploded data artifact
        uses: actions/download-artifact@v4
        with:
          name: exploded-carts

      - name: Download help.md artifact
        uses: actions/download-artifact@v4
        with:
          name: help-md
          path: tmp

      - name: Move help.md
        run: |
          mv tmp/help.md src/data/help.md

      - name: Generate version.json
        run: go run scripts/generate-version.go

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4